default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["CHAT_APP_DATABASE_HOST"] %>
  username: <%= ENV["CHAT_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["CHAT_APP_DATABASE_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: chat_app_development

production:
  <<: *default
  database: chat_app_production
